# Generated by Django 4.2.9 on 2024-01-29 05:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userauth', '0005_alter_usermodel_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.UUIDField(null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_item', to='userauth.usermodel')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
