# Generated by Django 4.2.9 on 2024-01-28 18:16

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.UUIDField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.UUIDField(null=True)),
                ('id', models.UUIDField(default=uuid.uuid1, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=50)),
                ('password', models.CharField(max_length=16, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
