# Generated by Django 4.2.9 on 2024-01-28 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_alter_usermodel_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklistedtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=500),
        ),
    ]
